/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.adservices.data.adselection;

import static com.google.common.truth.Truth.assertThat;

import static org.junit.Assert.assertThrows;

import android.adservices.common.CommonFixture;
import android.adservices.common.KeyedFrequencyCapFixture;
import android.database.sqlite.SQLiteConstraintException;

import androidx.room.Room;
import androidx.test.core.app.ApplicationProvider;

import com.android.adservices.service.adselection.HistogramEventFixture;

import org.junit.Before;
import org.junit.Test;

import java.time.temporal.ChronoUnit;

public class FrequencyCapDaoTest {
    private static final int ABSOLUTE_MAX_EVENT_COUNT = 10;
    private static final int LOWER_MAX_EVENT_COUNT = 9;
    FrequencyCapDao mFrequencyCapDao;

    @Before
    public void setup() {
        mFrequencyCapDao =
                Room.inMemoryDatabaseBuilder(
                                ApplicationProvider.getApplicationContext(),
                                SharedStorageDatabase.class)
                        .build()
                        .frequencyCapDao();
    }

    @Test
    public void testInsertNewHistogramIdentifier() {
        // Autogenerated row IDs are positive integers
        assertThat(
                        mFrequencyCapDao.insertNewHistogramIdentifier(
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER))
                .isGreaterThan(0);
    }

    @Test
    public void testGetMissingHistogramIdentifierForeignKeyIfExistsReturnsNull() {
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                "not found",
                                CommonFixture.VALID_BUYER_1,
                                CommonFixture.TEST_PACKAGE_NAME,
                                "not found CA"))
                .isNull();
    }

    @Test
    public void testGetHistogramIdentifierForeignKeyIfExists() {
        long rowId =
                mFrequencyCapDao.insertNewHistogramIdentifier(
                        DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getAdCounterKey(),
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getBuyer(),
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getCustomAudienceOwner(),
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getCustomAudienceName()))
                .isEqualTo(rowId);
    }

    @Test
    public void testInsertNewHistogramIdentifierWithSameForeignKeyThrows() {
        DBHistogramIdentifier originalIdentifier =
                DBHistogramIdentifierFixture.getValidDBHistogramIdentifierBuilder().build();

        long rowId = mFrequencyCapDao.insertNewHistogramIdentifier(originalIdentifier);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                originalIdentifier.getAdCounterKey(),
                                originalIdentifier.getBuyer(),
                                originalIdentifier.getCustomAudienceOwner(),
                                originalIdentifier.getCustomAudienceName()))
                .isEqualTo(rowId);

        // Add a different identifier with the same primary key (foreign key ID)
        DBHistogramIdentifier conflictingIdentifier =
                DBHistogramIdentifierFixture.getValidDBHistogramIdentifierBuilder()
                        .setHistogramIdentifierForeignKey(rowId)
                        .setBuyer(CommonFixture.VALID_BUYER_2)
                        .build();
        assertThrows(
                SQLiteConstraintException.class,
                () -> mFrequencyCapDao.insertNewHistogramIdentifier(conflictingIdentifier));

        // The old identifier should still be at the same row ID
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                originalIdentifier.getAdCounterKey(),
                                originalIdentifier.getBuyer(),
                                originalIdentifier.getCustomAudienceOwner(),
                                originalIdentifier.getCustomAudienceName()))
                .isEqualTo(rowId);
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                conflictingIdentifier.getAdCounterKey(),
                                conflictingIdentifier.getBuyer(),
                                conflictingIdentifier.getCustomAudienceOwner(),
                                conflictingIdentifier.getCustomAudienceName()))
                .isNull();
    }

    @Test
    public void testInsertNewHistogramEventData() {
        // Autogenerated row IDs are positive integers
        assertThat(
                        mFrequencyCapDao.insertNewHistogramEventData(
                                DBHistogramEventDataFixture.VALID_DB_HISTOGRAM_EVENT_DATA))
                .isGreaterThan(0);
    }

    @Test
    public void testInsertHistogramEventDataTwice() {
        // Autogenerated row IDs are positive integers
        long rowId1 =
                mFrequencyCapDao.insertNewHistogramEventData(
                        DBHistogramEventDataFixture.VALID_DB_HISTOGRAM_EVENT_DATA);
        long rowId2 =
                mFrequencyCapDao.insertNewHistogramEventData(
                        DBHistogramEventDataFixture.VALID_DB_HISTOGRAM_EVENT_DATA);

        assertThat(rowId1).isGreaterThan(0);
        assertThat(rowId2).isGreaterThan(0);
        assertThat(rowId1).isNotEqualTo(rowId2);
    }

    @Test
    public void testInsertHistogramEventDataTwiceWithSameRowIdThrows() {
        // Autogenerated row IDs are positive integers
        long sameRowId = 20;
        DBHistogramEventData sameRowIdEvent =
                DBHistogramEventDataFixture.getValidDBHistogramEventDataBuilder(
                                DBHistogramIdentifierFixture.VALID_FOREIGN_KEY)
                        .setRowId(sameRowId)
                        .build();
        assertThat(mFrequencyCapDao.insertNewHistogramEventData(sameRowIdEvent))
                .isEqualTo(sameRowId);
        assertThrows(
                SQLiteConstraintException.class,
                () -> mFrequencyCapDao.insertNewHistogramEventData(sameRowIdEvent));
    }

    @Test
    public void testInsertNullHistogramEventThrows() {
        assertThrows(
                NullPointerException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                null, ABSOLUTE_MAX_EVENT_COUNT, LOWER_MAX_EVENT_COUNT));
    }

    @Test
    public void testInsertHistogramEventInvalidAbsoluteMaxCountThrows() {
        assertThrows(
                IllegalArgumentException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                                0,
                                LOWER_MAX_EVENT_COUNT));
        assertThrows(
                IllegalArgumentException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                                -1,
                                LOWER_MAX_EVENT_COUNT));
    }

    @Test
    public void testInsertHistogramEventInvalidLowerMaxCountThrows() {
        assertThrows(
                IllegalArgumentException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                                ABSOLUTE_MAX_EVENT_COUNT,
                                0));
        assertThrows(
                IllegalArgumentException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                                ABSOLUTE_MAX_EVENT_COUNT,
                                -1));
    }

    @Test
    public void testInsertHistogramEventInvalidAbsoluteAndLowerMaxCountsThrows() {
        assertThrows(
                IllegalArgumentException.class,
                () ->
                        mFrequencyCapDao.insertHistogramEvent(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                                LOWER_MAX_EVENT_COUNT,
                                ABSOLUTE_MAX_EVENT_COUNT));
    }

    @Test
    public void testInsertNonWinHistogramEventAddsNewIdentifierAndData() {
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the histogram identifier was successfully added
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                null,
                                null))
                .isNotNull();

        // Verify that the event was successfully added with counts
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(1);
    }

    @Test
    public void testInsertWinHistogramEventAddsNewIdentifierAndData() {
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the histogram identifier was successfully added
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName()))
                .isNotNull();

        // Verify that the event was successfully added with counts
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(1);
    }

    @Test
    public void testInsertMultipleHistogramEventsAddsNewIdentifiersAndData() {
        // 3 events for buyer 1 (1 of which is a WIN) and 1 event for buyer 2
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the histogram identifiers were successfully added
        Long foreignKeyId =
                mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                        HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                        HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                        null,
                        null);
        assertThat(foreignKeyId).isNotNull();

        Long foreignKeyIdWin =
                mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                        HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                        HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                        HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getCustomAudienceOwner(),
                        HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getCustomAudienceName());
        assertThat(foreignKeyIdWin).isNotNull();

        Long foreignKeyIdDifferentBuyer =
                mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                        HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                .getAdCounterKey(),
                        HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER.getBuyer(),
                        null,
                        null);
        assertThat(foreignKeyIdDifferentBuyer).isNotNull();

        assertThat(foreignKeyId).isNotEqualTo(foreignKeyIdDifferentBuyer);
        assertThat(foreignKeyId).isNotEqualTo(foreignKeyIdWin);
        assertThat(foreignKeyIdWin).isNotEqualTo(foreignKeyIdDifferentBuyer);

        // Verify that the events were successfully added with counts
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(1)))
                .isEqualTo(2);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(1)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(1)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(1)))
                .isEqualTo(1);
    }

    @Test
    public void testInsertSameHistogramEventTwiceDoesNotThrow() {
        // Insert the first event and verify with counts
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(1);

        // Insert the second event and verify the counts increased
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(2);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1)))
                .isEqualTo(2);
    }

    @Test
    public void testInsertHistogramEventEvictsOldestEventsToLowerMax() {
        // Insert events for data with normal max thresholds (one at T-1, three at T+0, one at T+1)
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(5);

        // Insert another event with lower max thresholds to trigger eviction
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME, 5, 1);

        // The datastore was trimmed to the lower threshold, then the new event was persisted
        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(2);

        // Verify that only the oldest timestamps were removed
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()))
                .isEqualTo(1);

        // Verify that the new event was persisted
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()))
                .isEqualTo(1);
    }

    @Test
    public void testGetNumEventsForBuyerAfterTimeFromEmptyTables() {
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getAdCounterKey(),
                                DBHistogramIdentifierFixture.VALID_DB_HISTOGRAM_IDENTIFIER
                                        .getBuyer(),
                                DBHistogramEventDataFixture.VALID_DB_HISTOGRAM_EVENT_DATA
                                        .getAdEventType(),
                                DBHistogramEventDataFixture.VALID_DB_HISTOGRAM_EVENT_DATA
                                        .getTimestamp()))
                .isEqualTo(0);
    }

    @Test
    public void testGetNumEventsForBuyerAfterTimeWithDifferentTimes() {
        // Insert events for buyer 1 at T-1 and T+1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the events are found when searching for T-2
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(2)))
                .isEqualTo(2);

        // Verify that only one event is found when searching for T+0
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI))
                .isEqualTo(1);

        // Verify that only no event is found when searching for T+2
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.plusSeconds(2)))
                .isEqualTo(0);
    }

    @Test
    public void testGetNumEventsForBuyerAfterTimeWithDifferentBuyers() {
        // Insert an event for buyer 1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the event is found
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);

        // Insert the same event, but twice for buyer 2
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that only the appropriate buyers' events are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(2);
    }

    @Test
    public void testGetNumEventsForBuyerAfterTimeWithDifferentCustomAudiences() {
        // Insert an event for CA 1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the event is found
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);

        // Insert the same event, but twice for CA 2 with a different name
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that all events for the buyer are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(3);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(3);

        // Insert the same event, but twice for CA 3 with a different owner
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that all events for the buyer are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(6);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(6);
    }

    @Test
    public void testGetNumEventsForCustomAudienceAfterTimeFromEmptyTables() {
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getCustomAudienceName(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getTimestamp()))
                .isEqualTo(0);
    }

    @Test
    public void testGetNumEventsForCustomAudienceAfterTimeWithDifferentTimes() {
        // Insert events for buyer 1 at T-1 and T+1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the events are found when searching for T-2
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.minusSeconds(2)))
                .isEqualTo(2);

        // Verify that only one event is found when searching for T+0
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI))
                .isEqualTo(1);

        // Verify that only no event is found when searching for T+2
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                CommonFixture.FIXED_NOW_TRUNCATED_TO_MILLI.plusSeconds(2)))
                .isEqualTo(0);
    }

    @Test
    public void testGetNumEventsForCustomAudienceAfterTimeWithDifferentBuyers() {
        // Insert an event for buyer 1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the event is found
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);

        // Insert the same event, but twice for buyer 2
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that only the appropriate buyers' events are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(2);
    }

    @Test
    public void testGetNumEventsForCustomAudienceAfterTimeWithDifferentCustomAudiences() {
        // Insert an event for CA 1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that the event is found
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);

        // Insert the same event, but twice for CA 2 with a different name
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that all events for the buyer are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_NAME
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(2);

        // Insert the same event, but twice for CA 3 with a different owner
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that all events for the buyer are found
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getTimestamp()
                                        .minusSeconds(1L)))
                .isEqualTo(3);
    }

    @Test
    public void testDeleteHistogramEventDataBeforeTimeFromEmptyTables() {
        // Verify that this shouldn't throw an error
        assertThat(mFrequencyCapDao.deleteHistogramEventDataBeforeTime(CommonFixture.FIXED_NOW))
                .isEqualTo(0);
    }

    @Test
    public void testDeleteHistogramEventDataBeforeTime() {
        // Insert 1 event at T-1, 2 at T+0, and 3 at T+1
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Verify that deleting at T+0 only removes events at T-1
        assertThat(
                        mFrequencyCapDao.deleteHistogramEventDataBeforeTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getTimestamp()))
                .isEqualTo(1);

        // Verify that the rest of the events remain using counts
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(4);
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);
    }

    @Test
    public void testDeleteOldestHistogramEventDataFromEmptyTables() {
        // Verify that this shouldn't throw an error
        assertThat(mFrequencyCapDao.deleteOldestHistogramEventData(100)).isEqualTo(0);
    }

    @Test
    public void testDeleteOldestHistogramEventData() {
        // Insert events for data with normal max thresholds (one at T-1, three at T+0, one at T+1)
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(5);

        // Delete four events
        assertThat(mFrequencyCapDao.deleteOldestHistogramEventData(4)).isEqualTo(4);

        // Verify that there's only one event left
        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(1);

        // Verify that only the oldest timestamps were removed
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()))
                .isEqualTo(1);
    }

    @Test
    public void testDeleteExactNumOldestHistogramEventData() {
        // Insert four events for data with the same timestamps
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.getValidHistogramEventBuilder()
                        .setAdCounterKey(KeyedFrequencyCapFixture.KEY1)
                        .build(),
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.getValidHistogramEventBuilder()
                        .setAdCounterKey(KeyedFrequencyCapFixture.KEY2)
                        .build(),
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.getValidHistogramEventBuilder()
                        .setAdCounterKey(KeyedFrequencyCapFixture.KEY3)
                        .build(),
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.getValidHistogramEventBuilder()
                        .setAdCounterKey(KeyedFrequencyCapFixture.KEY4)
                        .build(),
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(4);

        // Verify that deleting three events only deletes three events
        assertThat(mFrequencyCapDao.deleteOldestHistogramEventData(3)).isEqualTo(3);

        // Verify that one event is left
        assertThat(mFrequencyCapDao.getTotalNumHistogramEvents()).isEqualTo(1);
    }

    @Test
    public void testDeleteUnpairedHistogramIdentifiersFromEmptyTables() {
        assertThat(mFrequencyCapDao.deleteUnpairedHistogramIdentifiers()).isEqualTo(0);
    }

    @Test
    public void testDeleteUnpairedHistogramIdentifiersOnlyPairedIdentifiers() {
        // Insert full events and matching identifiers
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        assertThat(mFrequencyCapDao.deleteUnpairedHistogramIdentifiers()).isEqualTo(0);

        // Verify that the identifiers are still there
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                null,
                                null))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName()))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                null,
                                null))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceName()))
                .isNotNull();
    }

    @Test
    public void testDeleteUnpairedHistogramIdentifiers() {
        // Insert both paired and unpaired identifiers
        mFrequencyCapDao.insertNewHistogramIdentifier(
                DBHistogramIdentifier.fromHistogramEvent(
                        HistogramEventFixture.VALID_HISTOGRAM_EVENT));
        mFrequencyCapDao.insertNewHistogramIdentifier(
                DBHistogramIdentifier.fromHistogramEvent(
                        HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER));
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Two unpaired identifiers are removed
        assertThat(mFrequencyCapDao.deleteUnpairedHistogramIdentifiers()).isEqualTo(2);

        // Verify that only the unpaired identifiers have been removed
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                null,
                                null))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getCustomAudienceName()))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName()))
                .isNotNull();
    }

    @Test
    public void testDeleteAllExpiredHistogramDataFromEmptyTables() {
        assertThat(mFrequencyCapDao.deleteAllExpiredHistogramData(CommonFixture.FIXED_NOW))
                .isEqualTo(0);
    }

    @Test
    public void testDeleteAllExpiredHistogramDataDeletesIdentifiers() {
        // Insert events for data (one at T-1, three at T+0, one at T+1)
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Delete the events earlier than T+1 (deletion is before and not inclusive)
        assertThat(
                        mFrequencyCapDao.deleteAllExpiredHistogramData(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()))
                .isEqualTo(4);

        // Verify the identifier and event is still there (same identifier, different time)
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getCustomAudienceName()))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);

        // Verify the other identifiers have been removed
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME.getBuyer(),
                                null,
                                null))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER
                                        .getBuyer(),
                                null,
                                null))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                null,
                                null))
                .isNull();
    }

    @Test
    public void testDeleteAllExpiredHistogramDataMultipleDeletes() {
        // Insert events for data (one at T-1, three at T+0, one at T+1)
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_LATER_TIME,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_HISTOGRAM_EVENT_DIFFERENT_BUYER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);
        mFrequencyCapDao.insertHistogramEvent(
                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER,
                ABSOLUTE_MAX_EVENT_COUNT,
                LOWER_MAX_EVENT_COUNT);

        // Delete the only event earlier than T+0 (deletion is before and not inclusive)
        assertThat(
                        mFrequencyCapDao.deleteAllExpiredHistogramData(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getTimestamp()))
                .isEqualTo(1);

        // Verify the correct events are still there
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME.getBuyer(),
                                null,
                                null))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_EARLIER_TIME
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(0);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName()))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(3);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(2);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceName()))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);

        // Delete all events prior to T+1
        assertThat(
                        mFrequencyCapDao.deleteAllExpiredHistogramData(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT_LATER_TIME
                                        .getTimestamp()))
                .isEqualTo(3);

        // Verify the correct events are still there
        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                null,
                                null))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(0);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName()))
                .isNotNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForBuyerAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT.getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(1);

        assertThat(
                        mFrequencyCapDao.getHistogramIdentifierForeignKeyIfExists(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceName()))
                .isNull();
        assertThat(
                        mFrequencyCapDao.getNumEventsForCustomAudienceAfterTime(
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdCounterKey(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getBuyer(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceOwner(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getCustomAudienceName(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getAdEventType(),
                                HistogramEventFixture.VALID_WIN_HISTOGRAM_EVENT_DIFFERENT_OWNER
                                        .getTimestamp()
                                        .minus(1, ChronoUnit.DAYS)))
                .isEqualTo(0);
    }
}
