register_toolchains(
    "//prebuilts/build-tools:py_toolchain",
    "//prebuilts/jdk/jdk17:runtime_toolchain_definition",
)

# `device_infra` repository provides rules needed to start cuttlefish devices
# remotely. This repository is loaded when Bazel needs a target from it,
# otherwise won't load.
local_repository(
    name = "device_infra",
    path = "vendor/google/tools/atest/device_infra",
)
