/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.tools.common.flicker.config

enum class FaasScenarioType {
    COMMON,
    LAUNCHER_APP_CLOSE_TO_HOME,
    LAUNCHER_APP_CLOSE_TO_PIP,
    LAUNCHER_APP_LAUNCH_FROM_ICON,
    LAUNCHER_APP_LAUNCH_FROM_RECENTS,
    LAUNCHER_APP_LAUNCH_FROM_WIDGET,
    LAUNCHER_APP_SWIPE_TO_RECENTS,
    LAUNCHER_CLOSE_ALL_APPS_SWIPE,
    LAUNCHER_CLOSE_ALL_APPS_TO_HOME,
    LAUNCHER_QUICK_SWITCH,
    NOTIFICATION_APP_START,
    LOCKSCREEN_LAUNCH_CAMERA,
    LOCKSCREEN_TRANSITION_FROM_AOD,
    LOCKSCREEN_TRANSITION_TO_AOD,
    LOCKSCREEN_UNLOCK_ANIMATION,
    SPLIT_SCREEN_ENTER,
    SPLIT_SCREEN_EXIT,
    SPLIT_SCREEN_RESIZE,
    SHADE_APP_LAUNCH_FROM_HISTORY_BUTTON,
    SHADE_APP_LAUNCH_FROM_MEDIA_PLAYER,
    SHADE_APP_LAUNCH_FROM_QS_TILE,
    SHADE_APP_LAUNCH_FROM_SETTINGS_BUTTON,
    STATUS_BAR_APP_LAUNCH_FROM_CALL_CHIP,
    NOTIFICATION_SHADE_EXPAND_COLLAPSE,
    NOTIFICATION_SHADE_EXPAND_COLLAPSE_LOCK,
    NOTIFICATION_SHADE_SCROLL_FLING,
    NOTIFICATION_SHADE_ROW_EXPAND,
    NOTIFICATION_SHADE_ROW_SWIPE,
    NOTIFICATION_SHADE_QS_EXPAND_COLLAPSE,
    NOTIFICATION_SHADE_QS_SCROLL_SWIPE,
    NOTIFICATION_HEADS_UP_APPEAR,
    NOTIFICATION_HEADS_UP_DISAPPEAR,
    NOTIFICATION_ADD,
    NOTIFICATION_REMOVE,
    LOCKSCREEN_PASSWORD_APPEAR,
    LOCKSCREEN_PATTERN_APPEAR,
    LOCKSCREEN_PIN_APPEAR,
    LOCKSCREEN_PASSWORD_DISAPPEAR,
    LOCKSCREEN_PATTERN_DISAPPEAR,
    LOCKSCREEN_PIN_DISAPPEAR,
    LAUNCHER_OPEN_ALL_APPS,
    LAUNCHER_ALL_APPS_SCROLL,
    SETTINGS_PAGE_SCROLL,
    PIP_TRANSITION,
    WALLPAPER_TRANSITION,
    USER_SWITCH,
    SPLASHSCREEN_AVD,
    SPLASHSCREEN_EXIT_ANIM,
    SCREEN_OFF,
    SCREEN_OFF_SHOW_AOD,
    ONE_HANDED_ENTER_TRANSITION,
    ONE_HANDED_EXIT_TRANSITION,
    UNFOLD_ANIM,
    SUW_LOADING_TO_SHOW_INFO_WITH_ACTIONS,
    SUW_SHOW_FUNCTION_SCREEN_WITH_ACTIONS,
    SUW_LOADING_TO_NEXT_FLOW,
    SUW_LOADING_SCREEN_FOR_STATUS,
    SETTINGS_SLIDER,
    TAKE_SCREENSHOT,
    VOLUME_CONTROL,
    BIOMETRIC_PROMPT_TRANSITION,
    SETTINGS_TOGGLE,
    SHADE_DIALOG_OPEN,
    USER_DIALOG_OPEN,
    TASKBAR_EXPAND,
    TASKBAR_COLLAPSE,
    SHADE_CLEAR_ALL,
    LAUNCHER_UNLOCK_ENTRANCE_ANIMATION,
    LOCKSCREEN_OCCLUSION,
    RECENTS_SCROLLING,
    IME_INSETS_ANIMATION,
}
