#
# CHRE API Test Nanoapp Makefile
#

# Makefile Includes ############################################################

include chre_api_test.mk

# Nanoapp Configuration ########################################################

NANOAPP_NAME = chre_api_test
NANOAPP_ID = 0x476f6f675400000d
NANOAPP_NAME_STRING = \"CHRE\ API\ Test\"
NANOAPP_VERSION = 0x00000001

# Compiler Flags ###############################################################

# Defines
COMMON_CFLAGS += -DLOG_TAG=\"[ChreApiTest]\"

# Makefile Includes ############################################################

include $(CHRE_PREFIX)/build/nanoapp/app.mk
